name = input("What is your name? ")
print("Hello! How are you, {0}?".format(name))

x="juxq"
for i in range(3):
    print("Hello! How are you, {0}?".format(name))"*i+x+" "*(7-i*0),x)
    print(" "*4,x)





#AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
#VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
#RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
#BBBBBBBBBBBBBBBBBBB  BBBBBBBBBBBBBBBBBBB
#YYYYYYYYYYYYYYYYY      YYYYYYYYYYYYYYYYY
#GGGGGGGGGGGGGGG          GGGGGGGGGGGGGGG
#CCCCCCCCCCCCC              CCCCCCCCCCCCC
#HHHHHHHHHHHH        H       HHHHHHHHHHHH
#GGGGGGGGGGGGG     GGGGG    GGGGGGGGGGGGG
#JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
#VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
#TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
